namespace: koonix
name: utils
version: 0.1.0
description: Some useful utilities
repository: https://github.com/koonix/ansible-collection-koonix.utils
issues: https://github.com/koonix/ansible-collection-koonix.utils/issues
authors:
  - koonix <me@koonix.org>
license:
  - Unlicense
tags:
  - collection
  - module
  - semver
  - github
  - dockerhub
  - vcs
  - scm
readme: README.md
